# Site settings
title: Endless Creation
email: ec2014e@gmail.com
description_main: EC 25th 신입생 종합 작품 개발 대회
description_sub: 2015년 11월 21일 토요일 미래관 313호
description_time: 오후 3시 부터 오후 7시까지
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Endless Creation
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/238730472850269/
  - title: github
    url: http://github.com/endlesscreation
  - title: users
    url: http://endlesscreation.kr
# Postal address (add as many lines as necessary)
address:
  - line: 서울과학기술대학교
  - line: 미래관 313호

# Credits content
credits: 
  university: '서울과학기술대학교 컴퓨터공학과'
  club: '학술동아리 Endless Creation'

# Build settings
markdown: kramdown
permalink: pretty


# Custom Collections
collections:
  members:
    output: true
